### ISSUE TITLE
There are frozen player objects from people who have disconnected repeatedly

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#238]
![screen shot 2017-02-04 at 12 26 26 pm 1](https://cloud.githubusercontent.com/assets/8272012/22621295/56955354-ead5-11e6-95d2-14d4dd908d03.png)
![screen shot 2017-02-04 at 12 25 04 pm](https://cloud.githubusercontent.com/assets/8272012/22621296/58348afe-ead5-11e6-8bce-21436aa89bb2.png)

**Comment by michaeljcalkins** [comment]
There is also period player spawn interpolation flashing but it's far less than what it was.

**Comment by And-re** [comment]
https://github.com/michaeljcalkins/rangersteve/pull/396

**Comment by michaeljcalkins** [comment]
@And-re I was playing this morning and still seeing this happen.

**Comment by michaeljcalkins** [comment]
@And-re You think this is fixed?

**Comment by And-re** [comment]
@michaeljcalkins I think it still happens from time to time but maybe it's because some players have an older version of the code (it's cached)
